apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: iq-server
  name: iq-server
spec:
  containers:
  - image: cmyanko/iq-server-k8s:1.72.0
    livenessProbe:
      exec:
        command:
        - curl
        - -f
        - http://iq-server:8071/ping
      failureThreshold: 3
      periodSeconds: 90
      timeoutSeconds: 10
    name: iq-server
    ports:
    - containerPort: 8070
    - containerPort: 8071
    resources: {}
    volumeMounts:
    - mountPath: /sonatype-work
      name: iq-data
    - mountPath: /opt/sonatype/nexus-iq-server/log
      name: iq-logs
  restartPolicy: OnFailure
  volumes:
  - name: iq-data
    persistentVolumeClaim:
      claimName: iq-data
  - name: iq-logs
    persistentVolumeClaim:
      claimName: iq-logs
status: {}
