apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-proxy
  name: nginx-proxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-proxy
    spec:
      containers:
      - args:
        - nginx
        - -g
        - daemon off;
        image: cmyanko/iq_nginx-proxy_k8s:2.6.1
        name: nginx-proxy
        ports:
        - containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}
